### ISSUE TITLE
Problem with auto-deploy on External switch and DHCP

### ISSUE THREAD

**Issue by arminghasemazar** [Azure/iotedge-eflow#188]
Hi.
I'm provisioning EFLOW on Azure VM with Windows Server 2019. I'm using Auto deploy functionality and my user config is as follow:
````
{
    "schemaVersion":"1.1",
    "version":"1.0",
    "eflowProduct": "Azure IoT Edge CR X64",
    "eflowProductUrl": "",
    "installOptions":{
        "installPath":"",
        "vhdxPath":""
    },
    "enduser":{
        "acceptEula": "Yes",
        "acceptOptionalTelemetry": "No"
    },
    "network":{
        "adapterName": "Ethernet",
        "vswitchName": "EFLOW",
        "vswitchType": "External",
        "ip4Address": "",
        "ip4GatewayAddress": "",
        "ip4PrefixLength": "",
        "useHostProxy": false,
        "httpProxy":"",
        "httpsProxy":"",
        "ftpProxy":"",
        "dnsServers":""
    },
    "vmConfig":{
        "cpuCount": 4,
        "memoryInMB": 4096,
        "vmDiskSize": 32,
        "vmDataSize": "",
        "gpuPassthroughType": "",
        "gpuName": "",
        "gpuCount": ""
    },
    "vmFeature":{
        "DpsTpm": false,
        "Defender": false
    },
    "eflowProvisioning":{
        "provisioningType": "DpsSymmetricKey",
        "devConnString": "",
        "iotHubHostname": "",
        "deviceId": "",
        "scopeId": "XXX",
        "symmKey": "XXX",
        "registrationId": "XXX",
        "identityCertPath": "",
        "identityPrivKeyPath": "",
        "globalEndpoint": ""
    }
}
````

However, I face an error of
`Deploy-Eflow : Cannot validate argument on parameter 'ip4PrefixLength'. The 0 argument is less than the minimum allowed range of 1. Supply an argument that is greater than or equal to 1 and then try the command again.` BUT, I can see that it has already created the external virtual switch correctly. 
![image](https://user-images.githubusercontent.com/13336488/195864587-96d8bf6a-cd91-4f4a-a275-19a6c07ae5a7.png)

So it basically searches for Prefix and "" doesn't have any meaning to the script in DHCP format. When I use 24, then it starts complaining about ip4Address and ip4GatewayAddress, which is understandable because it tries to assign IP. 

Am I missing something in my user config to apply DHCP?

Below is the execution log.

````
PS D:\EFLOW> .\eflowAutoDeploy.ps1 -AutoDeploy
Running eflowAutoDeploy version 1.0.220831.0800
HostOS	: Microsoft Windows Server 2019 Datacenter(8) 
Version	: 10.0.17763.3532 
Lang	: en-US 
Name	: vm-Edge-azar-wi
Total CPUs		: 2
Free RAM / Total RAM	: 14 GB / 16 GB
Free Disk / Total Disk	: 114 GB / 126 GB
Running as a virtual machine in Azure environment with Nested Hyper-V enabled
Azure IoT Edge,1.3.1.02092 is installed.
Loading D:\EFLOW\eflow-userconfig.json..
Hyper-V is enabled
Azure IoT Edge,1.3.1.02092 is installed.
Importing AzureEFLOW..
WARNING: The names of some imported commands from the module 'AzureEFLOW' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list 
of approved verbs, type Get-Verb.
AzureEFLOW Module:0.0.1
Hyper-V is enabled
* Using virtual switch EFLOW
* Using vSwitchType External
--- Verifying virtual switch IP address allocation...
* No static IP address provided - DHCP allocation or auto-static ip(internal switch) will be used
--- Checking proxy settings...
*** No errors found in the Network Configuration.
Creating VMSwitch EFLOW - External...

--- Verifying EFLOW VM Deployment Configuration...
--- Verifying EULA and telemetry...
* EULA accepted.
- Optional telemetry not accepted. Basic telemetry will be sent.
--- Verifying virtual switch...
Hyper-V is enabled
* Using virtual switch EFLOW
* Using vSwitchType External
--- Verifying virtual switch IP address allocation...
* No static IP address provided - DHCP allocation or auto-static ip(internal switch) will be used
--- Checking proxy settings...
*** No errors found in the Network Configuration.
* Name:EFLOW - Type:External
--- Verifying virtual machine resources...
* Virtual machine will be created with 4 vCPUs.
* Virtual machine will be created with 4096 MB of memory.
* Virtual machine VHDX will be created with 32 GB disk size.
* No custom data size used - Using default configuration, virtual machine VHDX will be created with 10 GB of data size.
--- Verifying GPU passthrough configuration...
* No GPU passthrough being used - CPU only allocation
*** No errors found in the Deployment Configuration.
Starting EFLOW VM deployment...
Deploy-Eflow : Cannot validate argument on parameter 'ip4PrefixLength'. The 0 argument is less than the minimum allowed range of 1. Supply an argument that is greater than or equal to 1 and then try the command again.
At D:\EFLOW\eflowAutoDeploy.ps1:726 char:28
+     $retval = Deploy-Eflow @eflowDeployParams
+                            ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Deploy-Eflow], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Deploy-Eflow
 
Error: EFLOW VM deployment failed with the below error message.
Error message : .
D:\EFLOW\eflowAutoDeploy.ps1 : Deployment failed
At line:1 char:1
+ .\eflowAutoDeploy.ps1 -AutoDeploy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,eflowAutoDeploy.ps1
 ````

**Comment by fcabrera23** [comment]
Hi @arminghasemazar,

There was an issue with empty string network parameters. I just pushed some changes to fix that. Could you please try it again?

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @arminghasemazar,

I fixed the first issue you mentioned. For the other two issues, I see that you're using Internal Switch, but your config file suggests you're using an External Switch. Could you please clariify?

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @arminghasemazar,

A couple of things you may try to change

1. If you're using "Internal" switch, the parameter "adapterName" is not needed, so you may want to leave that empty
2. For DNS servers, use the "dnsServers" field. This will set the DNS servers before trying to provision
3. If you still face the same issues, try restarting the IoT Edge service.

Thanks,
Franicsco

**Comment by arminghasemazar** [comment]
> Hi @arminghasemazar,
> 
> A couple of things you may try to change
> 
> 1. If you're using "Internal" switch, the parameter "adapterName" is not needed, so you may want to leave that empty
> 2. For DNS servers, use the "dnsServers" field. This will set the DNS servers before trying to provision
> 3. If you still face the same issues, try restarting the IoT Edge service.
> 
> Thanks, Franicsco

Hi Francisco.

Unfortunately same problems still persist. 

````
[10/20/2022 08:16:20] Virtual machine created successfully.


[10/20/2022 08:16:20] Successfully created virtual machine


[10/20/2022 08:16:20] Virtual machine hostname: vm-Edge-azar-ef-EFLOW


[10/20/2022 08:16:31] Error setting static IP


[10/20/2022 08:16:31] Testing SSH connection...


[10/20/2022 08:17:05] ...successfully connected to the Linux VM

 - Please check your DNS configuration to ensure Internet connectivity. Refer https://aka.ms/AzEFLOW-DNS for more details.

[10/20/2022 08:17:06] Deployment successful

* EFLOW VM deployment successfull.
Setting DNS Servers to 8.8.8.8 8.8.4.4

--- Verifying EFLOW VM Provisioning Configuration...
--- Verifying provisioning type...
* DpsSymmetricKey
--- Verifying provisioning parameters..
* scopeId Ok
* symmKey Ok
* registrationId Ok
No errors found in the Provisioning Configuration.
Starting EFLOW VM provisioning...

[10/20/2022 08:17:08] Provisioning virtual machine...


[10/20/2022 08:17:09] Provisioning iotedge for the first time.


[10/20/2022 08:17:09] Setting provisioning information for provisioning type: DpsSymmetricKey


[10/20/2022 08:17:31] Exception caught!!!

 - iotedge service not running after provisioning, please investigate manually at line 2416
Error: EFLOW provisioning failed with the below error message.
Error message : iotedge service not running after provisioning, please investigate manually.
D:\EFLOW\eflowAutoDeploy.ps1 : Deployment failed
At line:1 char:1
+ .\eflowAutoDeploy.ps1 -AutoDeploy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,eflowAutoDeploy.ps1
````

Result of `iotedge check`
````
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
‼ aziot-identity-service package is up-to-date - Warning
    Installed aziot-identity-service package has version 1.3.0 but 1.4.1 is the latest stable version available.
    Please see https://aka.ms/aziot-update-runtime for update instructions.
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
× read all preloaded certificates from the Certificates Service - Error
    could not load cert with ID "aziot-edged-trust-bundle"

    Caused by:
        parameter "id" has an invalid value
        caused by: not found
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (TimedOut) : Operation timed out
    One or more errors occurred. (Got bad response: )
‼ aziot-edge package is up-to-date - Warning
    Installed IoT Edge daemon has version 1.3.0 but 1.4.2 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
19 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.
4 check(s) raised errors. Re-run with --verbose for more details.
7 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.
````

Also, even though the provision script claims that it has set DNS servers, I cannot see them applied.
![image](https://user-images.githubusercontent.com/13336488/196896367-3b9fd707-9257-4822-a180-2c16579f8824.png)
And I think I know the reason because in the script there is only 
`Set-EflowVmDNSServers -dnsServers $eflowConfig.network.dnsServers`
while I also use
`Set-EflowVmDNSServers -vendpointName vm-Edge-azar-ef-EFLOWInterface -dnsServers @("8.8.8.8","8.8.4.4")`

In any case I don't think this DNS issue has anything to do with DPS provisioning. I also tried provisioning with device connection string and it went well and I can see the edge is working as it should. So there is something wrong with the DPS settings. Values for "scopeId", "symmKey", and "registrationId" are correct since I can provision a device on Ubuntu with similar values.

**Comment by arminghasemazar** [comment]
Some more logs:

journalctl -u aziot-certd
````
Oct 20 09:06:33 vm-Edge-azar-ef-EFLOW systemd[1]: Started Azure IoT Certificates Service.
Oct 20 09:06:33 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:06:33Z [INFO] - Starting service...
Oct 20 09:06:33 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:06:33Z [INFO] - Version - dev build
Oct 20 09:06:33 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:06:33Z [INFO] - Starting server...
Oct 20 09:06:33 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:06:33Z [INFO] - <-- GET /certificates/aziot-edged-trust-bundle?api-version=2020-09-01 {"host": "certd.sock"}
Oct 20 09:06:33 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:06:33Z [INFO] - !!! parameter "id" has an invalid value
Oct 20 09:06:33 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:06:33Z [INFO] - !!! caused by: not found
Oct 20 09:06:33 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:06:33Z [INFO] - --> 400 {"content-type": "application/json"}
Oct 20 09:07:06 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:07:06Z [INFO] - <-- GET /certificates/aziot-edged-trust-bundle?api-version=2020-09-01 {"host": "certd.sock"}
Oct 20 09:07:06 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:07:06Z [INFO] - !!! parameter "id" has an invalid value
Oct 20 09:07:06 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:07:06Z [INFO] - !!! caused by: not found
Oct 20 09:07:06 vm-Edge-azar-ef-EFLOW aziot-certd[3150]: 2022-10-20T09:07:06Z [INFO] - --> 400 {"content-type": "application/json"}
Oct 20 09:07:27 vm-Edge-azar-ef-EFLOW systemd[1]: Stopping Azure IoT Certificates Service...
Oct 20 09:07:27 vm-Edge-azar-ef-EFLOW systemd[1]: aziot-certd.service: Deactivated successfully.
Oct 20 09:07:27 vm-Edge-azar-ef-EFLOW systemd[1]: Stopped Azure IoT Certificates Service.
````

journalctl -u aziot-keyd
````
Oct 20 09:09:54 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:09:54Z [INFO] - <-- POST /sign?api-version=2020-09-01 {"host": "foo", "user-agent": "libcurl-agent/1.0", "accept": "*/*", "content-type": "application/json", "content-length": "146"}
Oct 20 09:09:54 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:09:54Z [INFO] - !!! parameter "handle" has an invalid value
Oct 20 09:09:54 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:09:54Z [INFO] - !!! caused by: invalid handle
Oct 20 09:09:54 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:09:54Z [INFO] - --> 400 {"content-type": "application/json"}
Oct 20 09:09:54 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:09:54Z [INFO] - <-- GET /key/defender_encryption_key?api-version=2020-09-01 {"host": "foo", "user-agent": "libcurl-agent/1.0", "accept": "*/*"}
Oct 20 09:09:54 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:09:54Z [INFO] - --> 200 {"content-type": "application/json"}
Oct 20 09:09:54 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:09:54Z [INFO] - <-- POST /decrypt?api-version=2020-09-01 {"host": "foo", "user-agent": "libcurl-agent/1.0", "accept": "*/*", "content-type": "application/json", "content-length": "1037"}
Oct 20 09:09:54 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:09:54Z [INFO] - --> 200 {"content-type": "application/json"}
````

iotedge system logs
````
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW systemd[1]: Started Azure IoT Identity Service.
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [INFO] - Starting service...
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [INFO] - Version - dev build
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [INFO] - Provisioning starting. Reason: Startup
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - <-- GET /key/defender_encryption_key?api-version=2020-09-01 {"host": "foo", "user-agent": "libcurl-agent/1.0", "accept": "*/*"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - --> 200 {"content-type": "application/json"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - <-- POST /decrypt?api-version=2020-09-01 {"host": "foo", "user-agent": "libcurl-agent/1.0", "accept": "*/*", "content-type": "application/json", "content-length": "1037"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - --> 200 {"content-type": "application/json"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - <-- GET /key/defender_encryption_key?api-version=2020-09-01 {"host": "foo", "user-agent": "libcurl-agent/1.0", "accept": "*/*"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - --> 200 {"content-type": "application/json"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - <-- POST /encrypt?api-version=2020-09-01 {"host": "foo", "user-agent": "libcurl-agent/1.0", "accept": "*/*", "content-type": "application/json", "content-length": "1012"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - --> 200 {"content-type": "application/json"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - --> 200 {"content-type": "application/json"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "406"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-keyd[4036]: 2022-10-20T09:13:34Z [INFO] - --> 200 {"content-type": "application/json"}
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [INFO] - Sending DPS registration request.
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [ERR!] - service encountered an error
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [ERR!] - caused by: DPS client error
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [ERR!] - caused by: invalid Content-Type; expected JSON
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]: 2022-10-20T09:13:34Z [ERR!] -    0: backtrace::backtrace::trace
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW aziot-identityd[5612]:    1: backtrace::capture::Backtrace::new
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Oct 20 09:13:34 vm-Edge-azar-ef-EFLOW systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
Oct 20 09:13:39 vm-Edge-azar-ef-EFLOW systemd[1]: aziot-identityd.service: Scheduled restart job, restart counter is at 115.
Oct 20 09:13:39 vm-Edge-azar-ef-EFLOW systemd[1]: Stopped Azure IoT Identity Service.
Oct 20 09:13:39 vm-Edge-azar-ef-EFLOW aziot-edged[4030]: 2022-10-20T09:13:39Z [WARN] - Failed to send HTTP request (attempt 2 of 2): connection error: Connection reset by peer (os error 104)
Oct 20 09:13:39 vm-Edge-azar-ef-EFLOW aziot-edged[4030]: 2022-10-20T09:13:39Z [ERR!] - Failed to obtain device identity: connection error: Connection reset by peer (os error 104)
Oct 20 09:13:39 vm-Edge-azar-ef-EFLOW aziot-edged[4030]: 2022-10-20T09:13:39Z [INFO] - Requesting device reprovision
Oct 20 09:13:39 vm-Edge-azar-ef-EFLOW aziot-edged[4030]: 2022-10-20T09:13:39Z [WARN] - Failed to clear provisioning cache before reprovision: No such file or directory (os error 2)
Oct 20 09:13:39 vm-Edge-azar-ef-EFLOW aziot-edged[4030]: 2022-10-20T09:13:39Z [WARN] - Failed to send HTTP request (attempt 1 of 2): error trying to connect: Permission denied (os error 13)
````

**Comment by fcabrera23** [comment]
Hi @arminghasemazar,

Thanks for your information. I tried your same config json and script and it worked for me, so I'm a bit confused. A couple of more questions

1) Have you tried using the normal installation without the script? Do you see the same "static IP" error?
2) Normal provisioning works right? Can we open a new issue in the [IoT Edge repo](https://github.com/Azure/azure-iotedge) for the DPS specific issue?

Thanks,
Francisco

**Comment by arminghasemazar** [comment]
> Hi @arminghasemazar,
> 
> Thanks for your information. I tried your same config json and script and it worked for me, so I'm a bit confused. A couple of more questions
> 
> 1. Have you tried using the normal installation without the script? Do you see the same "static IP" error?
> 2. Normal provisioning works right? Can we open a new issue in the [IoT Edge repo](https://github.com/Azure/azure-iotedge) for the DPS specific issue?
> 
> Thanks, Francisco

Hi Francisco.

It also confuses me a lot since the script is straightforward and shouldn't be any problem. 

1. Yes I see the same. But, I tried using the script on my personal computer and I didn't see the static IP problem. So most probably that issue is related to Azure VM. So we can ignore it. 
2. Yes normal provisioning works both with script and normal installation. Yes, agree, we need to open issue with IoT Edge repo. Will do that shortly. 

Thanks for your help BTW,

**Comment by arminghasemazar** [comment]
Just before creating a new issue in IoT Edge repo, I tried deploying EFLOW manually on my personal PC. I installed EFLOW X64 1.3.1.02092 and tried to deploy EFLOW with the following command:
`Deploy-Eflow -acceptEula Yes -acceptOptionalTelemetry No -cpuCount 1 -memoryInMB 4098 -vmDiskSize 22 -vswitchName "EFLOW" -vswitchType External`. But I am facing the following error. I'm using the latest version of Win 10 Pro with latest update. Hyper-V has been installed and an external switch is there and working. 
````
[10/21/2022 10:44:39] Setting dynamically expanding virtual hard disk maximum size to 23 GB

 - Creating storage vhd (file: AzureIoTEdgeForLinux-v1-EFLOW)
 - Creating vnic (name: DESKTOP-415VL1V-EFLOWInterface)
 - Instantiating virtual machine (name: DESKTOP-415VL1V-EFLOW)

[10/21/2022 10:44:46] Error: Virtual machine creation failed!


[10/21/2022 10:44:46] Cleaning up...


[10/21/2022 10:44:46] Exception caught!!!

 - C:\Program Files\Azure IoT Edge\nodectl.exe  compute vm show --name DESKTOP-415VL1V-EFLOW -o json failed to execute [Error: rpc error: code = NotFound desc = [Store] unable to filter entity from store for type[VirtualMachineInternal], FilterName[Name], FilterValue[DESKTOP-415VL1V-EFLOW]: Not Found] at line 4288

[10/21/2022 10:44:46] Exception caught!!!

 - Unable to create virtual machine. (L1229)

[10/21/2022 10:44:46] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh
````

**Comment by fcabrera23** [comment]
Hi @arminghasemazar,

Thanks for the update - We've been able to reproduce the Static IP issue, and we will fix it in our next update.
Regarding the VM creation error, could you please share the logs? Also, what's your free memory on the device?

Thanks,
Francisco

**Comment by arminghasemazar** [comment]
> 

Hey. Below is the full deploy log. The available free memory is 6 GB. I changed the deployment to 1 GB for memory and the same error still persists. 

````
PS C:\Users\armin> Deploy-Eflow -acceptEula Yes -acceptOptionalTelemetry No -cpuCount 1 -memoryInMB 1024 -vmDiskSize 22 -vswitchName "EFLOW" -vswitchType External

[10/24/2022 10:18:22] Deploying Azure IoT Edge for Linux on Windows

 - WARNING: This is a Public Preview version of Azure IoT Edge for Linux on Windows Continuous Release, not intended for production use.
 - WARNING: A clean install may be required for production use once the final General Availability (GA) release is available. For more information, check https://aka.ms/AzEFLOW-CR.
 - Configuration does not exist. Creating a default configuration...

[10/24/2022 10:18:22] Creating configuration

 - Configuration created successfully


[10/24/2022 10:18:23] Enabling Microsoft Update. This will allow Azure IoT Edge for Linux on Windows to receive updates.

 - Microsoft Update is enabled.

[10/24/2022 10:18:23] Step 1: Preparing host for Azure IoT Edge for Linux on Windows


[10/24/2022 10:18:23] Checking host for required features

 - Checking the status of 'Microsoft-Hyper-V'
 - Checking the status of 'Microsoft-Hyper-V-Management-PowerShell'
 - Checking the status of 'Microsoft-Hyper-V-Hypervisor'
 - Checking the status of 'OpenSSH.Client*'
 - Verifying whether Hyper-V is enabled and functional
 - Hyper-V core services are active

[10/24/2022 10:18:30] Checking for virtual switch with name 'EFLOW'

 - The virtual switch 'EFLOW' of type 'External' is present

[10/24/2022 10:18:31] Step 2: Validating pre-requisites and deployment parameters...

 - Verifying host requirements for selected configuration (22 GB disk size, 1024 MB memory, 1 CPUs)

[10/24/2022 10:18:31] Verifying Host OS can support requested EFLOW configuration


[10/24/2022 10:18:31] Verifying required storage, RAM and number of cores are available

 - Drive 'C:' has 35 GB free
 - A minimum of 24 GB disk space is required on drive 'C:'
 - Host has 5768 MB free memory
 - A minimum of 1024 MB memory is required
 - Host has 4 CPU cores
 - A minimum of 1 CPU cores is required

[10/24/2022 10:18:31] Step 3: Configuring Azure IoT Edge for Linux on Windows runtime


[10/24/2022 10:18:34] Associating wssdagent service with nodectl

 - Creating container (EflowStorageContainer)

[10/24/2022 10:18:35] Creating vnet (name: EFLOW)


[10/24/2022 10:18:36] Verifying installation

 - Verifying expected Windows host binaries
 - Verifying expected Linux VM image
 - Extracting Linux VM image
 - Testing for ssh key
 - Generating SSH key...
 - Testing for wssdagent service
 - Testing if wssdagent is running
 - Testing if container resource is provisioned
 - Testing if vnet resource 'EFLOW' is provisioned

[10/24/2022 10:19:05] Step 4: Runtime configuration complete. Creating virtual machine


[10/24/2022 10:19:09] Creating virtual machine. Verifying host requirements for selected configuration (13 GB disk size, 1024 MB memory, 1 CPUs)


[10/24/2022 10:19:09] Verifying Host OS can support requested EFLOW configuration


[10/24/2022 10:19:09] Verifying required storage, RAM and number of cores are available

 - Drive 'C:' has 33 GB free
 - A minimum of 13 GB disk space is required on drive 'C:'
 - Host has 5801 MB free memory
 - A minimum of 1024 MB memory is required
 - Host has 4 CPU cores
 - A minimum of 1 CPU cores is required

[10/24/2022 10:19:20] Setting dynamically expanding virtual hard disk maximum size to 23 GB

 - Creating storage vhd (file: AzureIoTEdgeForLinux-v1-EFLOW)
 - Creating vnic (name: DESKTOP-415VL1V-EFLOWInterface)
 - Instantiating virtual machine (name: DESKTOP-415VL1V-EFLOW)

[10/24/2022 10:19:26] Error: Virtual machine creation failed!


[10/24/2022 10:19:26] Cleaning up...


[10/24/2022 10:19:26] Exception caught!!!

 - C:\Program Files\Azure IoT Edge\nodectl.exe  compute vm show --name DESKTOP-415VL1V-EFLOW -o json failed to execute [Error: rpc error: code = NotFound desc = [Store] unable to filter entity from store for type[VirtualMachineInternal], FilterName[Name], FilterValue[DESKTOP-415VL1V-EFLOW]: Not Found] at line 4288

[10/24/2022 10:19:26] Exception caught!!!

 - Unable to create virtual machine. (L1229)

[10/24/2022 10:19:26] In order to attempt another deployment, please uninstall the Azure IoT Edge msi and start from fresh

Unable to create virtual machine.
````

**Comment by fcabrera23** [comment]
Hi @arminghasemazar.

Thanks for sharing that. Could you please share the WSSDAgent logs from `C:\ProgramData\wssdagent\logs`?

Thanks,
Francisco

**Comment by arminghasemazar** [comment]
> wssdagent

There are many folders in `C:\ProgramData\wssdagent\logs` that are all empty. Besides, there are three files, which I attach below. (I added .txt to all to be able to be able to upload here directly)
[agent-log-0.txt](https://github.com/Azure/iotedge-eflow/files/9854946/agent-log-0.txt)
[logconf.txt](https://github.com/Azure/iotedge-eflow/files/9854942/logconf.txt)
[wssdagent.log.txt](https://github.com/Azure/iotedge-eflow/files/9854943/wssdagent.log.txt)

Let me know if you can find something there.

**Comment by arminghasemazar** [comment]
> Hi @arminghasemazar.
> 
> Thanks for sharing that. Could you please share the WSSDAgent logs from `C:\ProgramData\wssdagent\logs`?
> 
> Thanks, Francisco

There are many folders in `C:\ProgramData\wssdagent\logs` that are all empty. Besides, there are three files, which I attach below. (I added .txt to all to be able to be able to upload here directly)
[agent-log-0.txt](https://github.com/Azure/iotedge-eflow/files/9854946/agent-log-0.txt)
[logconf.txt](https://github.com/Azure/iotedge-eflow/files/9854942/logconf.txt)
[wssdagent.log.txt](https://github.com/Azure/iotedge-eflow/files/9854943/wssdagent.log.txt)

Let me know if you can find something there.

**Comment by fcabrera23** [comment]
Hi Armin,

Thanks for sharing the logs. I do see that the WSSDAgent fails to create the EFLOW VM.  Could you please share the Windows version you're using? You can use `winver` command. 

Thanks,
Francisco

**Comment by arminghasemazar** [comment]
> Hi Armin,
> 
> Thanks for sharing the logs. I do see that the WSSDAgent fails to create the EFLOW VM. Could you please share the Windows version you're using? You can use `winver` command.
> 
> Thanks, Francisco

Hey. 
![image](https://user-images.githubusercontent.com/13336488/198231704-2ecd17c1-72a8-4dfd-840c-e0f6b3b512c8.png)

I I just tried to create an Ubuntu VM from inside the Hyper-V to test whether the Hyper-V is working and as you can see it is. So I don't see any issue with virtualization or PC config. 
![image](https://user-images.githubusercontent.com/13336488/198239838-bb6c382b-a923-4719-8b60-f420a4cb19af.png)

**Comment by fcabrera23** [comment]
Hi Armin,

This issue was fixed in the latest [EFLOW 1.4LTS](https://aka.ms/AzEFLOW-Update-1_4_1_13112) version. Please use this version to get the latest feature updates and CVEs fixes.

Thanks,
Francisco

**Comment by arminghasemazar** [comment]
> Hi Armin,
> 
> This issue was fixed in the latest [EFLOW 1.4LTS](https://aka.ms/AzEFLOW-Update-1_4_1_13112) version. Please use this version to get the latest feature updates and CVEs fixes.
> 
> Thanks, Francisco

Hi Franciso.

Thanks for the update. All other issues have been fixed. However, I still have problem with DPS symmetry key provision and I see the following error. I'm pretty sure I'm doing everything right and script and user config are correct. I also checked the config.yaml file and it looks ok. So something is wrong with 1.4.2 version while using EFLOW. I must say DPS provision within Ubuntu works fine (exactly the same device and same input). So seems like there are some inconsistency between EFLOW and DPS SymmetryKey. I'll  open a bug report in IoTEdge repo. 

````
Nov 15 14:38:56 LDKCPH03816-EFLOW aziot-identityd[8727]: 2022-11-15T14:38:56Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
Nov 15 14:38:56 LDKCPH03816-EFLOW aziot-identityd[8727]: 2022-11-15T14:38:56Z [ERR!] - service encountered an error
Nov 15 14:38:56 LDKCPH03816-EFLOW aziot-identityd[8727]: 2022-11-15T14:38:56Z [ERR!] - caused by: DPS client error
Nov 15 14:38:56 LDKCPH03816-EFLOW aziot-identityd[8727]: 2022-11-15T14:38:56Z [ERR!] - caused by: invalid Content-Type; expected JSON
Nov 15 14:38:56 LDKCPH03816-EFLOW aziot-identityd[8727]: 2022-11-15T14:38:56Z [ERR!] -    0: backtrace::capture::Backtrace::create
Nov 15 14:38:56 LDKCPH03816-EFLOW aziot-identityd[8727]:    1: backtrace::capture::Backtrace::new
Nov 15 14:38:56 LDKCPH03816-EFLOW systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 14:38:56 LDKCPH03816-EFLOW systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
````

**Comment by fcabrera23** [comment]
Hi @arminghasemazar,

Thanks for the clarification. If possible, could you please open a new issue with the logs and the error you're getting? I'll make sure to involve the IoT Edge team and try to troubleshoot the issue with them.

Thanks,
Francisco

**Comment by arminghasemazar** [comment]
> Hi @arminghasemazar,
> 
> Thanks for the clarification. If possible, could you please open a new issue with the logs and the error you're getting? I'll make sure to involve the IoT Edge team and try to troubleshoot the issue with them.
> 
> Thanks, Francisco

Hi Francisco.

I think I solved my issue. It is either my misinterpretation of EFLOW deploy configuration or it is really misleading :D 

So basically below is the correct interpretation:

> symmKey: it's the derived device key of the device NOT the primary key of the DPS enrollment group
> registrationId: It's the desired device name to be registered in the IoT hub NOT the derived device key.

And apparently the eflow provision function is not able to automatically generate derived key (based on device id and primary key of the dps). So one should first generate that device key (with the input of DPS primary key and device name) and then run the eflow deploy (with the input of device name and device key). 

BTW, I think you need to update Values of eflowProduct parameter in the JSON schema table. The current value for the latest 1.4 LTS is "Azure IoT Edge 1.4 LTS X64" but it's not seen in the table.

**Comment by fcabrera23** [comment]
Hi @arminghasemazar,

Thanks for the suggestions. I'll make sure to update the documentation and JSON schema table. 

Thanks,
Francisco
